# Generated by Django 6.0.4 on 2026-04-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='feedback',
            new_name='remark',
        ),
    ]
